server:
  port: 8081

spring:
  config:
    import: sm://
  # dice a Spring di non sostituire il tuo datasource configurato con uno in-memory
  test:
    database:
      replace: none
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${SUBSCRIPT_MANAGE_DB}
    username: ${sm://projects/782332691073/secrets/DB_USER/versions/1}
    password: ${sm://projects/782332691073/secrets/DB_PASSW/versions/1}
    driver-class-name: org.postgresql.Driver

  # Disabilita Cloud SQL autoconfigure per i test
  cloud:
    gcp:
      sql:
        enabled: false
      secretmanager:
        enabled: true

app:
  bootstrap:
    hmacKeyBase64: ${sm://projects/782332691073/secrets/BOOTSTRAP_HMAC_KEY_BASE64/versions/1}
  ca:
    # Secret Manager resource ids (version latest) o direttamente value via env
    issuingKeySecret: ${sm://projects/383163155925/secrets/CA_ISSUING_KEY_SECRET/versions/2} #${CA_ISSUING_KEY_SECRET}     # es: projects/<p>/secrets/issuingCA-key/versions/latest
    issuingCertSecret: ${sm://projects/383163155925/secrets/CA_ISSUING_CERT_SECRET/versions/2} #${CA_ISSUING_CERT_SECRET}   # es: projects/<p>/secrets/issuingCA-cert/versions/latest
    #chainSecret: ${sm://projects/383163155925/secrets/CA_CHAIN_SECRET/versions/1} #${CA_CHAIN_SECRET}                # opzionale; se non c'è, usa issuingCert come chain
  cert:
    validityDays: 365