steps:
  # =================================================================================
  # BUILD BUILDER STAGE (Cache Maven per velocizzare le successive 3 build)
  # =================================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-maven-builder'
    args: [
      'build',
      '--target', 'builder',
      '-t', 'maven-builder',
      '.'
    ]

  # =================================================================================
  # BUILD DEI SERVIZI
  # =================================================================================
  # Build ADMIN-SERVICE
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-admin'
    args: [
      'build',
      '--build-arg', 'SERVICE_NAME=admin-service',
      '--cache-from', 'maven-builder',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service:$COMMIT_SHA',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service:latest',
      '.'
    ]
    waitFor: ['build-maven-builder']

  # Build ENROLLMENT-SERVICE
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-enrollment'
    args: [
      'build',
      '--build-arg', 'SERVICE_NAME=enrollment-service',
      '--cache-from', 'maven-builder',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service:$COMMIT_SHA',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service:latest',
      '.'
    ]
    waitFor: ['build-maven-builder']

  # Build INGEST-SERVICE
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ingest'
    args: [
      'build',
      '--build-arg', 'SERVICE_NAME=ingest-service',
      '--cache-from', 'maven-builder',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service:$COMMIT_SHA',
      '-t', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service:latest',
      '.'
    ]
    waitFor: ['build-maven-builder']

  # =================================================================================
  # PUSH DELLE IMMAGINI
  # =================================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-admin'
    args: ['push', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service', '--all-tags']
    waitFor: ['build-admin']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-enrollment'
    args: ['push', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service', '--all-tags']
    waitFor: ['build-enrollment']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ingest'
    args: ['push', 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service', '--all-tags']
    waitFor: ['build-ingest']

  # =================================================================================
  # DEPLOY SU CLOUD RUN
  # =================================================================================
  # Deploy ADMIN-SERVICE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-admin'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'admin-service'
      - '--image'
      - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service:$COMMIT_SHA'
      - '--region'
      - 'europe-west12'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'l1-control-plane-sa@mosqhealthagent.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'ENROLLMENT_URL=${_ENROLLMENT_URL},SUBSCRIPT_MANAGE_DB_SCHEMA=${_SUBSCRIPT_MANAGE_DB_SCHEMA},SUBSCRIPT_MANAGE_DB=${_SUBSCRIPT_MANAGE_DB}'
      - '--add-cloudsql-instances'
      - '${_SUBSCRIPT_MANAGE_DB}'
    waitFor: ['push-admin']

  # Deploy ENROLLMENT-SERVICE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-enrollment'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'enrollment-service'
      - '--image'
      - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service:$COMMIT_SHA'
      - '--region'
      - 'europe-west12'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'l1-control-plane-sa@mosqhealthagent.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'ENROLLMENT_URL=${_ENROLLMENT_URL},SUBSCRIPT_MANAGE_DB_SCHEMA=${_SUBSCRIPT_MANAGE_DB_SCHEMA},SUBSCRIPT_MANAGE_DB=${_SUBSCRIPT_MANAGE_DB}'
      - '--add-cloudsql-instances'
      - '${_SUBSCRIPT_MANAGE_DB}'
    waitFor: ['push-enrollment']

  # Deploy INGEST-SERVICE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ingest'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ingest-service'
      - '--image'
      - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service:$COMMIT_SHA'
      - '--region'
      - 'europe-west12'
      - '--platform'
      - 'managed'
      # --allow-unauthenticated rimosso o modificabile a seconda dei settaggi LB. Per test MVP aggiunto:
      - '--allow-unauthenticated'
      - '--service-account'
      - 'l1-control-plane-sa@mosqhealthagent.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'ENROLLMENT_URL=${_ENROLLMENT_URL},SUBSCRIPT_MANAGE_DB_SCHEMA=${_SUBSCRIPT_MANAGE_DB_SCHEMA},SUBSCRIPT_MANAGE_DB=${_SUBSCRIPT_MANAGE_DB}'
      - '--add-cloudsql-instances'
      - '${_SUBSCRIPT_MANAGE_DB}'
    waitFor: ['push-ingest']

substitutions:
  _ENROLLMENT_URL: 'https://tuo-dominio.com/v1/enrollment'
  _SUBSCRIPT_MANAGE_DB: 'mosqhealthagent:europe-west12:control-plan-gateway-db'
  _SUBSCRIPT_MANAGE_DB_SCHEMA: 'subscript_manage_db'

options:
  #dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service:$COMMIT_SHA'
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/admin-service:latest'
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service:$COMMIT_SHA'
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/enrollment-service:latest'
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service:$COMMIT_SHA'
  - 'europe-west12-docker.pkg.dev/mosqhealthagent/control-plane-repo/ingest-service:latest'
