server:
  address: 0.0.0.0
  port: ${PORT:8082}

spring:
  application:
    name: ingest-service
  config:
    import: sm://
  # dice a Spring di non sostituire il tuo datasource configurato con uno in-memory
  test:
    database:
      replace: none
  data:
    mongodb:
      uri: mongodb://${sm://projects/782332691073/secrets/DB_USER/versions/2}:${sm://projects/782332691073/secrets/DB_PASSW/versions/2}@6b676047-d20d-4f5d-8f4b-f5fe474068b9.us-central1.firestore.goog:443/control-plane-gateway-fb?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

  cloud:
    gcp:
      secretmanager:
        enabled: true

app:
  ca:
    issuingCertSecret: ${sm://projects/782332691073/secrets/CA_ISSUING_CERT_SECRET/versions/1}
  pubsub:
    topic: projects/mosqhealthagent/topics/edge-telemetry
  cache:
    allowTtlMinutes: 10
    denyTtlSeconds: 90
    maximumSize: 50000