server:
  port: ${PORT:8083} # admin-service might be on 8080 or random port, so we use 8081 by default for the webapp

spring:
  application:
    name: webapp-service
  security:
    user:
      name: admin
      password: password123
      roles: ADMIN

app:
  admin-service:
    url: ${ADMIN_SERVICE_URL:http://localhost:8080/v1/admin}
